INFO:root:The arg value for generate_dataframe is False
INFO:root:2020-11-04 08:47:09.792396: Connecting to database...
